import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

// @ts-ignore
import 'animate.css'
// @ts-ignore
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const bgUrl = "https://cloud.dragoncode.dev/f/J6WsK/whitedragon115_a_stylized_night_forest_scene_with_glowing_north_21a0830c-ac68-4306-bf57-6538ce0b79d8.png";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script type="module">
          import "https://font.emtech.cc/emfont.js";
          emfont.init();
        </script>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
        style={{
          background: `url('${bgUrl}')`,
          backgroundSize: "cover",
          backgroundPosition: "center",
          backgroundRepeat: "no-repeat",
          backgroundAttachment: "fixed",
        }}
      >
        {children}
      </body>
    </html>
  );
}